########################################
# Proxy Configuration
########################################

proxy.port=8080

########################################
# HttpClient
########################################

proxy.connect.timeout=5
proxy.request.timeout=30

########################################
# Health Check
########################################

health.interval=5
health.timeout=2

########################################
# Backends
########################################

backend.1.host=localhost
backend.1.port=8081

backend.2.host=localhost
backend.2.port=8082

backend.3.host=localhost
backend.3.port=8083